from typing import Protocol, List, Any

class ProjectDAO(Protocol):
    def save_project(self, project: Any) -> None: ...
    def load_project(self, project_id: str) -> Any: ...
    def list_projects(self) -> List[str]: ...
    def delete_project(self, project_id: str) -> None: ...